[package]
name = "ladata"
description = "A simple & modular data model."
version = "0.0.22"
edition = "2021"
resolver = "2"
# MSRV because: GATs, let-else
rust-version = "1.65" # https://releases.rs/docs/1.65.0/
authors = ["José Luis Cruz <joseluis@andamira.net>"]
repository = "https://github.com/andamira/ladata"
documentation = "https://docs.rs/ladata"
license = "MIT/Apache-2.0"
include = [
	"/src/**/*.rs",
	"/Cargo.toml",
	"/LICENSE-*",
	"/README.md",
]
categories = [ "no-std", "data-structures" ]
keywords = [ "data", "type", "cell" ] # dataframe
publish = true

[dependencies]
paste = "1.0.10"
nonmax = "0.5.3"

# feature: "deps_continuous" (continuous numbers):
half = { version = "2.0.0", optional = true, default-features = false } # F16 BF16
twofloat = { version = "0.5.0", optional = true, default-features = false } # F128

# feature: "deps_discrete" (discrete numbers):
num-rational = { version = "0.4.1", optional = true } # Ratio
num-bigint = { version = "0.4.3", optional = true } # BigInt
rust_decimal = { version = "1.25.0", optional = true } # Decimal

# feature: "deps_string" (strings):
arraystring = { version = "0.3.0", optional = true } # ArrayString*

# feature: "dep_datetime" (date/time):
fugit = { version = "0.3.6", optional = true }
time = { version = "0.3.11", optional = true }

# feature: "dep_bit" (bit arrays):
bv = { version = "0.11.1", optional = true } # BitArray* (impl `Bits`)

[features]
default = [ "std", "deps_default" ]
std = [ "half?/std" ]
no_unsafe = []

deps_all = [
	"deps_numerical",
	"deps_categorical",
]
deps_default = [
	#"deps_numerical",
		"deps_discrete",
		#"deps_continuous",
			"half", "twofloat",
	#"deps_categorical",
		"deps_bit",
		"deps_string",
		#"deps_datetime",
			"time", # !"fugit",
]

deps_numerical= ["deps_continuous", "deps_discrete"]
deps_continuous = ["half", "twofloat"]
deps_discrete = ["num-rational", "num-bigint", "rust_decimal"]

deps_categorical = ["deps_bit", "deps_datetime", "deps_string"]
deps_bit = ["bv"]
deps_datetime = ["fugit", "time"]
deps_string =  ["arraystring"]

[dev-dependencies]

[package.metadata.docs.rs]
features = ["deps_all"]

[badges]
maintenance = { status = "actively-developed" }
