[package]
name = "ladata"
description = "data structures"
version = "0.0.3"
edition = "2021"
rust-version = "1.58.1"
authors = ["José Luis Cruz <joseluis@andamira.net>"]
repository = "https://github.com/andamira/ladata"
documentation = "https://docs.rs/ladata"
license = "MIT/Apache-2.0"
include = [
	"src/**/*.rs",
	"Cargo.toml",
	"LICENSE*",
	"README.md",
]
categories = [ "data-structures" ]
keywords = [ "data", "dataframe" ]
publish = false

[dependencies]
# byte = "0.2.6"

[dev-dependencies]

[badges]
# https://doc.rust-lang.org/cargo/reference/manifest.html#the-badges-section
maintenance = { status = "actively-developed" }
