[package]
name = "ladata"
description = "data model"
version = "0.0.11"
edition = "2021"
rust-version = "1.59"
authors = ["José Luis Cruz <joseluis@andamira.net>"]
repository = "https://github.com/andamira/ladata"
documentation = "https://docs.rs/ladata"
license = "MIT/Apache-2.0"
include = [
	"src/**/*.rs",
	"Cargo.toml",
	"LICENSE*",
	"README.md",
]
categories = [ "no-std", "data-structures" ]
keywords = [ "data", "dataframe" ]
publish = false

[dependencies]
paste = "1"

# numbers: continuous
half = { version = "1.8.2", optional = true } # F16 BF16
softposit = { version = "0.3.9", optional = true } # P8, P16, P32, Q8, Q16, Q32
twofloat = { version = "0.4.1", optional = true } # F128

# numbers: discrete
num-rational = { version = "0.4.0", optional = true } # Ratio
num-bigint = { version = "0.4.3", optional = true } # BitInt
rust_decimal = { version = "1.22.0", optional = true } # Decimal

# strings
arraystring = { version = "0.3.0", optional = true } # ArrayString*

# time
fugit = { version = "0.3.5", optional = true }
time = { version = "0.3.7", optional = true }

[features]
default = [ "std", "deps_all" ]
std = [ ]
deps_all = [
	"deps_continuous",
	"deps_discrete",
	"deps_string",
	"deps_time",
]
deps_continuous = [ "half", "softposit", "twofloat" ]
deps_discrete = [ "num-rational", "num-bigint", "rust_decimal" ]
deps_string =  [ "arraystring" ]
deps_time = [ "fugit", "time" ]

[dev-dependencies]

[badges]
maintenance = { status = "actively-developed" }
