[package]
name = "ladata"
description = "data model"
version = "0.0.8"
edition = "2021"
rust-version = "1.59"
authors = ["José Luis Cruz <joseluis@andamira.net>"]
repository = "https://github.com/andamira/ladata"
documentation = "https://docs.rs/ladata"
license = "MIT/Apache-2.0"
include = [
	"src/**/*.rs",
	"Cargo.toml",
	"LICENSE*",
	"README.md",
]
categories = [ "no-std", "data-structures" ]
keywords = [ "data", "dataframe" ]
publish = false

[dependencies]
paste = "1"

half = "1.8.2" # F16 BF16
softposit = "0.3.9" # P8, P16, P32, Q8, Q16, Q32
twofloat = "0.4.1" # F128

num-rational = "0.4.0"
num-bigint = "0.4.3"
rust_decimal = "1.22.0"

arrayvec = "0.7.2" # ArrayString

[features]
default = [ "std" ]
std = [ ]

[dev-dependencies]

[badges]
maintenance = { status = "actively-developed" }
