[package]
name = "ladata"
description = "WIP data frame like table"
version = "0.0.1"
edition = "2018"
authors = ["José Luis Cruz <joseluis@andamira.net>"]
# repository = "https://github.com/andamira/ladata"
# documentation = "https://docs.rs/ladata"
license = "MIT/Apache-2.0"
include = [
	"**/*.rs",
	"Cargo.toml",
	"LICENSE*",
	"README.md",
]
categories = []
keywords = []
publish = false

[dependencies]
paste = "1.0.5"

[dev-dependencies]
float_eq = "0.6.1"

[build-dependencies]
# docima = "0.9.1"

[package.metadata.docs.rs]
# rustdoc-args = [ "--html-in-header", "./src/docs-header.html" ]
